/**
 * tests/helpers/asRole.ts — docs/build/05-test-plan.md §1.3 `asRole` / `asUser` contracts (real from S1.1).
 *
 *   asRole('anon')    → anon key, no session
 *   asRole('service') → service-role key (bypasses RLS; arrange state / prove "service can")
 *   asRole('user' | 'banned' | 'mod' | 'admin' | 'nohandle' | 'user0')
 *                     → anon key + the matching SEED-3 user's JWT (05 §1.4 role → seed identity)
 *   asUser(profileId) → anon key + the JWT of a factory-created user (`makeUser`, tests/helpers/factories.ts)
 *
 * Seeded clients are built synchronously: the JWT is resolved lazily through supabase-js's `accessToken`
 * option on the first request, by `signInWithPassword({ email: 'seed-<x>@localhost.test', password:
 * 'seed-password' })` against the local stack, and the session is cached per identity for the process
 * (one sign-in per role per test file — the `db` project runs one file per fork). Consequence: these
 * clients serve `.from()` / `.rpc()` / `.storage` under RLS as that user, but `client.auth.*` is not
 * available on them (supabase-js disables it when `accessToken` is set) — for code that needs a real
 * cookie session (`lib/auth.ts getUser()`) use `callAction` (mocked server client) or
 * `seedSessionCookies()` from tests/helpers/sessionCookies.ts.
 *
 * Env comes from `.env.test` (loaded by tests/helpers/setup.db.ts): local stack only, no real key (H-9).
 * tests/** may import @supabase/supabase-js directly (the app-side fence, 01 INV-13, is for app code).
 */
import { createClient, type Session, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '@/lib/supabase/types';
import { assertLocalSupabase, requireTestEnv } from './envTest';
import { SEED_USERS } from './seedIds';

export type SeedRole = 'user' | 'banned' | 'mod' | 'admin' | 'nohandle' | 'user0';
export type TestRole = 'anon' | SeedRole | 'service';

export type TestClient = SupabaseClient<Database>;

// ---- Loose (schema-agnostic) view ------------------------------------------------------------
// `lib/supabase/types.ts` is regenerated by supabase-ops every slice; harness code that is table-driven
// (expectPolicy, factories) must compile before AND after a regen, so it drives this loose shape.
type LooseTable = {
  Row: Record<string, unknown>;
  Insert: Record<string, unknown>;
  Update: Record<string, unknown>;
  Relationships: [];
};
type LooseDatabase = {
  public: {
    Tables: Record<string, LooseTable>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
export type LooseClient = SupabaseClient<LooseDatabase>;

/** The same client, typed against any table name / any columns (for table-driven helpers only). */
export function loose(client: TestClient): LooseClient {
  return client as unknown as LooseClient;
}

export type Credentials = { email: string; password: string };

/** SEED-3 local password (05 §3; local/preview only — production Auth is Google-only, H-9). */
export const SEED_PASSWORD = 'seed-password';

/** 05 §1.4 role → SEED-3 identity. */
export const SEED_ROLE_EMAILS: Readonly<Record<SeedRole, string>> = {
  user: 'seed-user@localhost.test', // …0003 seed_user
  banned: 'seed-banned@localhost.test', // …0005 seed_banned
  mod: 'seed-mod@localhost.test', // …0002 seed_mod
  admin: 'seed-admin@localhost.test', // …0001 oddsense
  nohandle: 'seed-newbie@localhost.test', // …0006 handle NULL
  user0: 'seed-user2@localhost.test', // …0004 seed_user2, comment_count 0
};

/** 05 §1.4 role → SEED-3 profile id (tests/helpers/seedIds.ts). */
export const SEED_ROLE_IDS: Readonly<Record<SeedRole, string>> = {
  user: SEED_USERS.seed_user,
  banned: SEED_USERS.seed_banned,
  mod: SEED_USERS.seed_mod,
  admin: SEED_USERS.oddsense,
  nohandle: SEED_USERS.seed_newbie,
  user0: SEED_USERS.seed_user2,
};

const SEED_ROLES: ReadonlySet<string> = new Set(Object.keys(SEED_ROLE_EMAILS));

export function isSeedRole(role: string): role is SeedRole {
  return SEED_ROLES.has(role);
}

/** Factory users (tests/helpers/factories.ts) are created as `t_<profileId>@localhost.test`. */
export function factoryEmail(profileId: string): string {
  return `t_${profileId}@localhost.test`;
}

export function credentialsFor(role: SeedRole): Credentials {
  return { email: SEED_ROLE_EMAILS[role], password: SEED_PASSWORD };
}

// Factories may register a different email for a profile id (asUser falls back to factoryEmail()).
const emailByProfileId = new Map<string, string>();

export function registerUserEmail(profileId: string, email: string): void {
  emailByProfileId.set(profileId, email);
}

export function credentialsForUser(profileId: string): Credentials {
  return {
    email: emailByProfileId.get(profileId) ?? factoryEmail(profileId),
    password: SEED_PASSWORD,
  };
}

function supabaseUrl(): string {
  const url = requireTestEnv('NEXT_PUBLIC_SUPABASE_URL');
  assertLocalSupabase(url, 'asRole');
  return url;
}

function baseClient(key: string, accessToken?: () => Promise<string | null>): TestClient {
  return createClient<Database>(supabaseUrl(), key, {
    auth: { persistSession: false, autoRefreshToken: false },
    ...(accessToken ? { accessToken } : {}),
  });
}

// ---- Session cache (per process = per db test file) ----------------------------------------

const sessions = new Map<string, Session>();

function isFresh(session: Session): boolean {
  // Re-sign-in when the JWT is within 60 s of expiry (local `jwt_expiry` is 3600 s).
  return session.expires_at === undefined || session.expires_at * 1000 - Date.now() > 60_000;
}

/** Password sign-in on the local stack, cached per email. Throws with the GoTrue message on failure. */
export async function signIn(creds: Credentials): Promise<Session> {
  const cached = sessions.get(creds.email);
  if (cached && isFresh(cached)) return cached;
  const { data, error } = await baseClient(
    requireTestEnv('NEXT_PUBLIC_SUPABASE_ANON_KEY'),
  ).auth.signInWithPassword(creds);
  if (error || !data.session) {
    throw new Error(
      `asRole: sign-in as ${creds.email} failed: ${error?.message ?? 'no session'} — ` +
        'is SEED-3 applied (supabase db reset) / was the factory user created?',
    );
  }
  sessions.set(creds.email, data.session);
  return data.session;
}

/** Drops a cached session (factories call it when they delete a user). */
export function forgetSession(email: string): void {
  sessions.delete(email);
}

/** The access token (JWT) for a seed role — for `Authorization: Bearer` style assertions. */
export async function accessTokenFor(role: SeedRole): Promise<string> {
  return (await signIn(credentialsFor(role))).access_token;
}

// ---- Clients ---------------------------------------------------------------------------------

function clientForCredentials(creds: Credentials): TestClient {
  return baseClient(
    requireTestEnv('NEXT_PUBLIC_SUPABASE_ANON_KEY'),
    async () => (await signIn(creds)).access_token,
  );
}

/** Returns a typed Supabase client acting as `role` against the local stack (05 §1.3). */
export function asRole(role: TestRole): TestClient {
  switch (role) {
    case 'anon':
      return baseClient(requireTestEnv('NEXT_PUBLIC_SUPABASE_ANON_KEY'));
    case 'service':
      return baseClient(requireTestEnv('SUPABASE_SERVICE_ROLE_KEY'));
    default:
      if (isSeedRole(role)) return clientForCredentials(credentialsFor(role));
      throw new Error(`asRole: unknown role "${String(role)}"`);
  }
}

/** Same as `asRole` for an arbitrary factory-created user (05 §1.3 `asUser`). */
export function asUser(profileId: string): TestClient {
  return clientForCredentials(credentialsForUser(profileId));
}
